### ISSUE TITLE
Using a Smart Group to limit listing

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-directory#2]
Using the Profile to built a directory, there is the setting to limit the contact listing by Group, in a lot of cases a smart group. This allows you to say show me all member who are active of member type x, but not those who are lapsed for example. 

This is part of the advanced settings in a profile
![limit-listings-by-group](https://user-images.githubusercontent.com/1139085/30117125-57863740-92ed-11e7-9d4c-1beea3568ce1.png)

> Limit Group
> Select a group if you are using this profile for search and listings, AND you want to limit the listings to members of a specific group.   

This is useful, as it provides flexibility to display a directory by any criteria used in an advanced search to create a smart group.

**Comment by christianwach** [comment]
This is now implemented. Am closing the ticket - we can continue the discussion on #1 if we want an option to switch to Membership instead of Group determining inclusion in the directory.
