### ISSUE TITLE
Default core contact fields

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-directory#3]
Core contact types to start with are:

**Individuals** 

* Prefix
* First Name
* Middle Name
* Last Name
* Suffix 
* Current Employer
* Job title
* Contact Type
* Gender
* Birth Date 

**Organizations**

* Organization Name
* Legal Name
* Sic Code
* Contact Type

**Fields in both contact types**

* Nickname
* Email
* Phone  
* Website
* Contact Source
* External ID
* Upload Image
* Address fields

After these the use of Custom Fields would be the next step to extend/customize the data fields in a directory listing.

**Comment by danaskallman** [comment]
Using CiviCRM Profiles to then select and display in a Directory will have the same limitations, for example you  can only use fields from the same contact type.

Wonder if something like is done with tokens can be done, or maybe just select from a list of tokens like with mailings?

![build-directory-tokens-list](https://user-images.githubusercontent.com/1139085/30492954-5b32bf38-9a10-11e7-9f9b-ed735a1185c6.png)

Then for example I can be listed as an individual point of contact but the details are organizations address or phone number.

**Comment by danaskallman** [comment]
Custom Fields in tokens are something like this `{contact.custom_11}`

**Comment by danaskallman** [comment]
Adding screenshot of custom field token display

![build-directory-tokens-custom-field](https://user-images.githubusercontent.com/1139085/30493735-66d4697e-9a13-11e7-8bcf-445885567cea.png)

**Comment by christianwach** [comment]
I think this is handled through a combination of (a) the checkboxes available on the back-end of a Directory and (b) the template system. Have I missed something?

**Comment by danaskallman** [comment]
Yeah, this is a good start. I think anything else we can add new issues for as we get requests or feedback.
