### ISSUE TITLE
Map Height per Directory

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-directory#6]
Is there a way to add a setting in each directory to set map height? Maybe width too, though that tends to be 100% so it's responsive. However height could vary based on what is being mapped. Thoughts on how this could be done?

**Comment by christianwach** [comment]
With 0.2.8, Maps now have a default height (set on admin screen) but each Directory can override this setting.

**Comment by danaskallman** [comment]
Sweet, this is great and works...thanks!
